accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts.views import signup

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    Receipt,
    ReceiptCreateView,
    ReceiptListView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,
    AccountListView,
    AccountCreateView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="categories_list",
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account, related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


# Create your views here.
def signup(request):
    if request.method == "POST":
        print(request.method)
        print(request.POST)
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})

receipts/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from receipts.models import Receipt, ExpenseCategory, Account
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        receipt = form.save(commit=False)
        receipt.purchaser = self.request.user
        receipt.save()
        return redirect("home")


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/category_create.html"
    fields = ["name"]

    def form_valid(self, form):
        category = form.save(commit=False)
        category.owner = self.request.user
        category.save()
        return redirect("categories_list")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/category_list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/account_create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        account = form.save(commit=False)
        account.owner = self.request.user
        account.save()
        return redirect("account_list")


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/account_list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Expenses</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <li>
                            <a href="{% url 'signup' %}">Sign Up</a>
                        </li>
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

receipts/templates/receipts/account_create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>Create Account</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/account_list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>My Accounts</h1>
            <table>
                <thead>
                    <tr>
                        <th colspan='2'>Name</th>
                        <th colspan='2'>Number</th>
                        <th colspan='2'>Number of receipts</th>
                    </tr>
                </thead>
                <tbody>
                    {% for account in account_list %}
                        <tr>
                            <td colspan='2'>{{ account }}</td>
                            <td colspan='2'>{{ account.number }}</td>
                            <td colspan='2'>{{ account.receipts.all | length }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/category_create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>Create Category</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/category_list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>My Categories</h1>
            <table>
                <thead>
                    <tr>
                        <th colspan='2'>Name</th>
                        <th colspan='2'>Number of receipts</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in expensecategory_list %}
                        <tr>
                            <td colspan='2'>{{ category }}</td>
                            <td colspan='2'>{{ category.receipts.all | length }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <nav>
            <ul>
                <li>
                    <a href="{% url 'categories_list' %}">Categories</a>
                </li>
                <li>
                    <a href="{% url 'account_list' %}">Accounts</a>
                </ul>
                <ul>
                    <li>
                        <a href="{% url 'create_receipt' %}">Create new receipt</a>
                    </li>
                    <li>
                        <a href="{% url 'create_category' %}">Create new category</a>
                    </li>
                    <li>
                        <a href="{% url 'create_account' %}">Create new account</a>
                    </li>
                </ul>
            </nav>
            <h1>My Receipts</h1>
            <table>
                <thead>
                    <tr>
                        <th colspan='2'>Vendor</th>
                        <th colspan='2'>Total</th>
                        <th colspan='2'>Tax</th>
                        <th colspan='2'>Date</th>
                        <th colspan='2'>Category</th>
                        <th colspan='2'>Account</th>
                    </tr>
                </thead>
                <tbody>
                    {% for receipt in receipt_list %}
                        <tr>
                            <td colspan='2'>{{ receipt.vendor }}</td>
                            <td colspan='2'>{{ receipt.total }}</td>
                            <td colspan='2'>{{ receipt.tax }}</td>
                            <td colspan='2'>{{ receipt.date }}</td>
                            <td colspan='2'>{{ receipt.category }}</td>
                            <td colspan='2'>{{ receipt.account }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    {% endblock content %}